### ISSUE TITLE
C^2MEngine incompatibility

### ISSUE THREAD

**Issue by Felix14-v2** [Spottedleaf/lightbench#1]
**Description**
Joining the world with lightbench and [c2me](https://github.com/ishlandbukkit/C2ME-fabric) installed causes a crash.

**To reproduce**
- Install Fabric 1.17.1
- Install [C2ME](https://github.com/ishlandbukkit/C2ME-fabric/releases/download/0.2.0%2Balpha.5/c2me-fabric-mc1.17.1-0.2.0+alpha.5.0-all.jar) and [Lightbench](https://github.com/Spottedleaf/lightbench/releases/download/1.0.2/lightbench-1.0.2-1.17.jar)
- Launch Minecraft
- Try to join world or create it
- See the crash

**Info**
Minecraft: 1.17.1
Fabric: 0.11.7
Lightbench: 1.0.2
C2ME: 0.2.0 alpha 5.0

**Logs**
[latest.log](https://github.com/Spottedleaf/lightbench/files/7486326/latest.log)

**Other**
Compatibility issue on C2ME repository: [#78](https://github.com/ishlandbukkit/C2ME-fabric/issues/78)

**Comment by Spottedleaf** [comment]
only designed to be compatible with starlight/phosphor/vanilla
