### ISSUE TITLE
Crash with Minecraft 1.19+

### ISSUE THREAD

**Issue by Felix14-v2** [Spottedleaf/lightbench#2]
Lightbench seems to be incompatible with Minecraft 1.19+, could you update it in your free time?

[latest.log](https://github.com/Spottedleaf/lightbench/files/11288483/latest.log)
[crash-2023-04-20_19.11.03-client.txt](https://github.com/Spottedleaf/lightbench/files/11288484/crash-2023-04-20_19.11.03-client.txt)

**Comment by Spottedleaf** [comment]
Only will be updated for 1.20+
